version: '3.1'

# rodar o command 'docker-compose --env-file ./.env up -d' para conseguir subir o banco de dados com as variaveis de ambiente

services:

  mongo:
    image: mongo
    container_name: mongo-database
    restart: always
    environment:
    
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  mongo-express:
    image: mongo-express
    container_name: mongo-express-name
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
